"""baseline schema

Revision ID: 4441cb12cadd
Revises: 
Create Date: 2026-06-15 20:21:13.608778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4441cb12cadd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('isin', sa.String(length=32), nullable=True),
    sa.Column('series', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_symbol'), ['symbol'], unique=True)

    op.create_table('company_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'kind', name='uq_insight_symbol_kind')
    )
    with op.batch_alter_table('company_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_insights_symbol'), ['symbol'], unique=False)

    op.create_table('sentiment_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('overall', sa.Float(), nullable=True),
    sa.Column('technical', sa.Float(), nullable=True),
    sa.Column('fundamental', sa.Float(), nullable=True),
    sa.Column('news', sa.Float(), nullable=True),
    sa.Column('ownership', sa.Float(), nullable=True),
    sa.Column('market', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_sentiment_symbol_date')
    )
    with op.batch_alter_table('sentiment_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentiment_scores_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentiment_scores_symbol'), ['symbol'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_stripe_customer_id'), ['stripe_customer_id'], unique=False)

    op.create_table('ai_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_reports_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_reports_symbol'), ['symbol'], unique=False)

    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_rules_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_rules_user_id'), ['user_id'], unique=False)

    op.create_table('financial_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('period_type', sa.String(length=16), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('ebit', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_liabilities', sa.Float(), nullable=True),
    sa.Column('current_liabilities', sa.Float(), nullable=True),
    sa.Column('total_equity', sa.Float(), nullable=True),
    sa.Column('operating_cash_flow', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period', 'period_type', name='uq_fin_company_period')
    )
    with op.batch_alter_table('financial_statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_statements_company_id'), ['company_id'], unique=False)

    op.create_table('news_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('news', sa.String(length=1024), nullable=True),
    sa.Column('event', sa.String(length=64), nullable=True),
    sa.Column('sentiment_label', sa.String(length=16), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('signal', sa.String(length=16), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('published_at', sa.String(length=64), nullable=True),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_signals_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_signals_signal'), ['signal'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_signals_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_signals_uid'), ['uid'], unique=True)

    op.create_table('portfolio_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_holding_user_symbol')
    )
    with op.batch_alter_table('portfolio_holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_holdings_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_holdings_user_id'), ['user_id'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_price_company_date')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_date'), ['date'], unique=False)

    op.create_table('research_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=80), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('sources_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_chats_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_chats_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_chats_user_id'), ['user_id'], unique=False)

    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', 'metric', name='uq_usage_user_day_metric')
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_records_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_user_id'), ['user_id'], unique=False)

    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_watchlist_user_symbol')
    )
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_user_id'), ['user_id'], unique=False)

    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_events_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_seen'), ['seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_events_symbol'))
        batch_op.drop_index(batch_op.f('ix_alert_events_seen'))
        batch_op.drop_index(batch_op.f('ix_alert_events_rule_id'))

    op.drop_table('alert_events')
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_user_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_symbol'))

    op.drop_table('watchlist')
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_day'))

    op.drop_table('usage_records')
    with op.batch_alter_table('research_chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_chats_user_id'))
        batch_op.drop_index(batch_op.f('ix_research_chats_symbol'))
        batch_op.drop_index(batch_op.f('ix_research_chats_created_at'))

    op.drop_table('research_chats')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_date'))
        batch_op.drop_index(batch_op.f('ix_price_history_company_id'))

    op.drop_table('price_history')
    with op.batch_alter_table('portfolio_holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_holdings_user_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_holdings_symbol'))

    op.drop_table('portfolio_holdings')
    with op.batch_alter_table('news_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_signals_uid'))
        batch_op.drop_index(batch_op.f('ix_news_signals_ticker'))
        batch_op.drop_index(batch_op.f('ix_news_signals_signal'))
        batch_op.drop_index(batch_op.f('ix_news_signals_company_id'))

    op.drop_table('news_signals')
    with op.batch_alter_table('financial_statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_statements_company_id'))

    op.drop_table('financial_statements')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_rules_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_rules_symbol'))

    op.drop_table('alert_rules')
    with op.batch_alter_table('ai_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_reports_symbol'))
        batch_op.drop_index(batch_op.f('ix_ai_reports_company_id'))

    op.drop_table('ai_reports')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('sentiment_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentiment_scores_symbol'))
        batch_op.drop_index(batch_op.f('ix_sentiment_scores_date'))

    op.drop_table('sentiment_scores')
    with op.batch_alter_table('company_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_insights_symbol'))

    op.drop_table('company_insights')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_symbol'))

    op.drop_table('companies')
    # ### end Alembic commands ###
